theme: jekyll-theme-minimal
title: SciryLab
description: SciryLab, a digital solutions factory
logo: https://res.cloudinary.com/scirylab/image/upload/v1598564173/website_cdn/undraw_work_together_h63l_hdwjg2.png
